name: build-karthus
on: push

jobs:
    build-karthus:
        name: build the project
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2.3.3
              with:
                lfs: true

            - name: cache
              uses: actions/cache@v1.1.0
              with:
                path: Library
                key: Library

            - name: unity - builder
              uses: webbertakken/unity-builder@v1.4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              with:
                unityVersion: 2020.1.2f1
                targetPlatform: StandaloneWindows64 

            - uses: actions/upload-artifact@v1
              with:
                name: Build
                path: build
