name: Build Game
on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
    build-karthus:
        name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
        runs-on: ubuntu-latest


        steps:
            - uses: actions/checkout@v2.3.3
              with:
                lfs: true

            - uses: actions/cache@v1.1.0
              with:
                path: Library
                key: Library

            - name: Build project
              uses: webbertakken/unity-builder@v1.4
              with:
                versioning: Semantic
                unityVersion: 2020.1.2f1
                targetPlatform: StandaloneWindows64

            - uses: actions/upload-artifact@v1
              with:
                name: Build
                path: build
